# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Práticas
    url: docs/
    weight: 20
  - name: Datasets
    url: blog/
    weight: 30
  - name: Autores
    url: showcase/
    weight: 40
  - name: Community
    url: community/
    weight: 50

sidebar:
  - identifier: more
    name: Still need help?
    params:
      type: separator
    weight: 1
  - identifier: community
    name: "Community"
    pageRef: "/community"
    weight: 2
  - identifier: hugoDocs
    name: "Hugo Docs ↗"
    url: "https://docs.hugoblox.com"
    weight: 3
